import type { Meta, StoryObj } from '@storybook/react';
import { Activity, BarChart3, HeartHandshake } from 'lucide-react';
import { ProgressChart, SampleWorkout, VideoPlayer } from '../Features';
import FeatureCard from './FeatureCard';

/**
 * FeatureCard component documentation
 */
const meta: Meta<typeof FeatureCard> = {
  title: 'features/Homepage/Features/components/FeatureCard',
  component: FeatureCard,
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
    backgrounds: {
      default: 'dark',
    },
    docs: {
      description: {
        component: 'A flip card component that displays feature information with a hover effect to reveal a demo component.'
      },
    },
  },
  argTypes: {
    title: {
      description: 'The title of the feature',
      control: 'text'
    },
    description: {
      description: 'The description of the feature',
      control: 'text'
    },
    icon: {
      description: 'React node to display as the feature icon'
    },
    gradient: {
      description: 'Tailwind gradient classes for the icon background',
      control: 'text'
    },
    demoComponent: {
      description: 'React component to display on the back of the card'
    },
    isActive: {
      description: 'Whether the feature is currently active',
      control: 'boolean'
    }
  },
};

export default meta;
type Story = StoryObj<typeof FeatureCard>;

/**
 * AI Feature Card example
 */
export const AIWorkout: Story = {
  args: {
    title: 'AI-Powered Workouts',
    description: 'Get personalized workout plans generated by our advanced AI algorithm based on your goals, fitness level, and preferences.',
    icon: <BarChart3 size={48} className="text-lime-300 group-hover:scale-110 transition-transform duration-300" />,
    gradient: 'from-lime-300/20 to-emerald-500/20',
    demoComponent: <SampleWorkout />,
    isActive: false,
    onMouseEnter: () => { },
    onMouseLeave: () => { }
  },
  parameters: {
    docs: {
      description: {
        story: 'Feature card showcasing AI workout generation with a sample workout demo.'
      }
    }
  }
};

/**
 * Progress Tracking Feature
 */
export const FormAnalysis: Story = {
  args: {
    title: 'Real-Time Form Analysis',
    description: 'Our AI technology analyzes your exercise form in real-time to prevent injuries and ensure proper technique.',
    icon: <Activity size={48} className="text-lime-300 group-hover:scale-110 transition-transform duration-300" />,
    gradient: 'from-lime-300/20 to-cyan-500/20',
    demoComponent: <ProgressChart />,
    isActive: false,
    onMouseEnter: () => { },
    onMouseLeave: () => { }
  },
  parameters: {
    docs: {
      description: {
        story: 'Feature card showcasing form analysis with a progress chart demo.'
      }
    }
  }
};

/**
 * Expert Trainers Feature
 */
export const ExpertAdvice: Story = {
  args: {
    title: 'Expert Advice',
    description: 'Receive guidance and tips from professional fitness experts.',
    icon: <HeartHandshake size={48} className="text-lime-300 group-hover:scale-110 transition-transform duration-300" />,
    gradient: 'from-lime-300/20 to-purple-500/20',
    demoComponent: <VideoPlayer />,
    isActive: false,
    onMouseEnter: () => { },
    onMouseLeave: () => { }
  },
  parameters: {
    docs: {
      description: {
        story: 'Feature card showcasing expert advice with a video player demo.'
      }
    }
  }
};

/**
 * Community Feature
 */
export const CommunityFeature: Story = {
  args: {
    title: 'Community Support',
    description: 'Join our fitness community to share experiences, get motivation, and connect with others on a similar fitness journey.',
    icon: 'users'
  },
  parameters: {
    docs: {
      description: {
        story: 'Feature card highlighting community support with the users icon.',
      },
    },
  },
};
