name: Lighthouse CI

on:
  push:
    branches: [ main, perf/critical-css-homepage ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: Install serve
        run: npm install -g serve
        
      - name: Start server and run Lighthouse CI
        run: |
          serve dist -l 8080 &
          sleep 5
          mkdir -p lighthouse-results
          npx @lhci/cli@0.11.x autorun --outputDir=./lighthouse-results
          
      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-results
          path: ./lighthouse-results
