name: Storybook Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.storybook/**'
      - 'package.json'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.storybook/**'
      - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      STORYBOOK_DISABLE_TELEMETRY: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cache/storybook
          key: ${{ runner.os }}-storybook-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-storybook-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Lint stories
        run: npx eslint "src/**/*.stories.{js,jsx,ts,tsx}" --max-warnings=0
        
      - name: Build Storybook
        run: npm run build-storybook
        
      - name: Upload Storybook build artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-build
          path: storybook-static
          
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          target-folder: storybook
          
      - name: Run Chromatic visual testing
        if: github.event_name == 'pull_request'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: 'build-storybook'
          exitZeroOnChanges: true
          onlyChanged: true
          externals: |
            ['src/assets/**/*'] 